# file: ceph-preinstall.yml
# invocation: ansible-playbook -i hosts ceph-preinstall.yml
#
# edit /etc/ansible/hosts to include all ceph rhscs,mon,osds,rgws 
#
# https://access.redhat.com/documentation/en-us/red_hat_ceph_storage/3/html-single/installation_guide_for_red_hat_enterprise_linux/

---
- hosts: all
  gather_facts: no
  tasks:
    - yum: name=firewalld state=present
    - systemd: name=firewalld enabled=yes state=started

- hosts: mons
  gather_facts: no
  vars: 
    mon_repos:
      - rhel-7-server-rhceph-2-mon-rpms
      - rhel-7-server-rhscon-2-agent-rpms
    mon_ports:
      - 6789/tcp
      - 8002/tcp
  tasks:
    - name: Enable repo for Ceph Mons
      command: subscription-manager repos --enable={{ item }}
      with_items: "{{ mon_repos }}"

    - name: Configure MON Firewall
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      with_items: "{{ mon_ports }}"


- hosts: osds
  gather_facts: no
  vars:
    osd_repos:
      - rhel-7-server-rhceph-2-osd-rpms
      - rhel-7-server-rhscon-2-agent-rpms
    osd_ports:
      - 6800-7300/tcp

  tasks:
    - name: Enable repo for Ceph OSDs
      command: subscription-manager repos --enable={{ item }}
      with_items: "{{ osd_repos }}"

    - name: Configure OSD Firewall
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      with_items: "{{ osd_ports }}"


- hosts: rgws
  gather_facts: no
  vars:
    rgw_repos:
      - rhel-7-server-rhceph-2-tools-rpms
    rgw_ports:
      - 80/tcp
      - 443/tcp
      - 7480/tcp

  tasks:
    - name: Enable repo for Ceph RGWs
      command: subscription-manager repos --enable={{ item }}
      with_items: "{{ rgw_repos }}"

    - name: Configure RGW Firewall
      firewalld:
        port: "{{ item }}"
        permanent: true
        state: enabled
      with_items: "{{ rgw_ports }}"

#    - name: Install RGW
#      yum: 
#        name: ceph-radosgw
#        state: present
