# file: ocp-rpm-preinstall.yml
# Authors: Mike Flannery (mflanner@redhat.com) & John Call (jcall@redhat.com)
# Invocation: ansible-playbook ocp-rpm-preinstall.yml
#
# Updated: April 5th, 2018 for OCP/CNS 3.9

# https://access.redhat.com/documentation/en-us/openshift_container_platform/3.9/html-single/installation_and_configuration/#install-config-install-advanced-install

---
- hosts: all
  become: true
  vars: 
    repos: #dynamically populated below

#  vars_prompt:
#    - name: "rhsm_username"
#      prompt: "Enter RHN/RHSM Username"
#      private: no
#
#    - name: "rhsm_password"
#      prompt: "Enter RHN/RHSM Password"
#      private: yes
#
#    - name: "poolid"
#      prompt: "Enter Red Hat Pool ID"
#      private: no

  tasks:
  - block:
    - name: Register with Red Hat
      redhat_subscription:
        state: present
        username: "{{ rhsm_username }}"
        password: "{{ rhsm_password }}"
        autosubscribe: false
      async: 300
      poll: 10
  
    - name: Attach Pool
      command: subscription-manager attach --pool={{ poolid }}
      async: 300
      poll: 10
    tags: [rhsm]
    # end block

  - block:
    - set_fact:
        repos: "{{ repos }} --enable={{ item }}"
      no_log: true
      with_items:
        - rhel-7-server-rpms
        - rhel-7-server-extras-rpms
        - rhel-7-server-ansible-2.4-rpms
        - rhel-7-server-ose-3.9-rpms
        - rhel-7-fast-datapath-rpms
        - rh-gluster-3-client-for-rhel-7-server-rpms

    - name: Disable all repos
      command: subscription-manager repos --disable="*"

    - name: Enable repos
      command: subscription-manager repos {{ repos }} 
    tags: [repos]
    when: ansible_distribution_major_version == "7"
    #end block

  - name: Install required RPMs
    yum:
      name: "{{ item }}"
      state: latest
    with_items:
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - kexec-tools
      - sos
      - psacct
      - atomic-openshift-utils
      - docker-1.13.1
    tags: [rpms]

  - block:
#    - name: "Extend /dev/sda1"
#      command: growpart /dev/sda 1
  
#    - name: "Grow /dev/sda1"
#      command: xfs_growfs /
  
    - name: "Setup docker-storage-setup"
      copy:
        content: |
          STORAGE_DRIVER=devicemapper
          DEVS=/dev/sdb
          VG=docker_vg
          CONTAINER_THINPOOL=docker_pool
        dest: /etc/sysconfig/docker-storage-setup
  
    - name: "Run docker-storage-setup"
      command: docker-storage-setup
  
    - name: "Start and enable docker"
      systemd:
        unit: docker.service
        state: restarted
        enabled: yes
    tags: [ test ]
    # end block

#  - name: Reboot to apply any updates, and clear cloud-init state
#    command: systemctl reboot
#    tags: reboot
