# https://github.com/oVirt/ovirt-ansible-image-template.git
# Requires: libselinux-python
# 2min 30sec @ ansible-playbook ovirt-mktemplate.yml -e qcow_url="file:///home/jcall/Downloads/rhel-server-7.5-x86_64-kvm.qcow2" -e template_disk_storage=vmstore --ask-vault-pass
---
- name: Make oVirt template
  hosts: localhost
  connection: local
  gather_facts: true
  vars_files:
    - "{{ ansible_domain }}/rhvm-vault.yml"

  vars:
    engine_url: "{{ rhvurl }}"
    engine_user: "{{ rhvuser }}"
    engine_password: "{{ rhvpass }}"
    engine_cafile: /etc/pki/ovirt-engine/ca.pem

    #qcow_url: file:///root/jcall/rhel-server-7.5-x86_64-kvm.qcow2
    qcow_url: https://access.cdn.redhat.com//content/origin/files/sha256/7f/7ff0d81ebf68119816b2756b7ed591dc9b50d29713e3785cc6bed564429a8b04/rhel-server-7.5-update-1-x86_64-kvm.qcow2?_auth_=1532552481_c2b5a955a0090bf7460ba47e7d64e967
    template_cluster: Default
    template_name: rhel75
    template_memory: 2GiB
    template_cpu: 2
#    template_disk_interface: virtio-scsi
    template_disk_size: 10GiB
    template_disk_storage: ssd-vmstore

  roles:
    - ovirt-ansible-image-template
