---
- hosts: all
  gather_facts: no
  become: yes
  tasks:
  - name: Copy binary and script to hosts
    copy:
      src: "./Penguin_Computing_Red_Hat_Configure_UEFI-SCELNX_64"
      dest: "/usr/local/bin/SCELNX_64"
      mode: preserve
  - name: Run the script
    script: ./Penguin_Computing_Red_Hat_Configure_UEFI.sh
    args:
      creates: /root/bios-configured-by-jcall
    tags: [ batch ]
