# file: redhat-register-single-file.yml
# $ ansible-playbook redhat-register-single-file.yml --ask-vault-pass -u root -k

---
- hosts: all
  vars:
    employee_sku_physical: 8a85f98a60c09b100160c40fd5ff63dc
    employee_sku_virtual: 8a85f98a60c09b100160c40fd82d63fb
    repos:
    repo_list:
      - rhel-7-server-rpms
#      - rhel-7-server-extras-rpms
#      - rhel-7-server-optional-rpms
#      - rhel-ha-for-rhel-7-server-rpms
#      - rh-gluster-3-for-rhel-7-server-rpms
#      - rh-gluster-3-nfs-for-rhel-7-server-rpms
#      - rh-gluster-3-samba-for-rhel-7-server-rpms
#      - rh-gluster-3-nagios-for-rhel-7-server-rpms

  vars_prompt:
    - prompt: "Enter RHN/RHSM Username"
      name: "rhsm_user"
      private: no
    - prompt: "Enter RHN/RHSM Password"
      name: "rhsm_pass"
      private: yes

  tasks:
    - name: Register with Red Hat
      block:
      - redhat_subscription:
           state: present
           username: "{{ rhsm_user }}"
           password: "{{ rhsm_pass }}"
           autosubscribe: false
        serial: 2
        async: 300
        poll: 10
      
      - name: Attach my Employee Subscription (physical)
        command: subscription-manager attach --pool={{ employee_sku_physical }}
        when: ansible_virtualization_role != "guest"
        serial: 2
        async: 300
        poll: 10
      
      - name: Attach my Employee Subscription (virtual)
        command: subscription-manager attach --pool={{ employee_sku_virtual }}
        when: ansible_virtualization_role == "guest"
        async: 300
        poll: 10
      tags: [ rhsm ]
      # end block

    - name: Enable repos
      block:
      - set_fact:
          repos: "{{ repo_list | join(' --enable=') }}"
      - debug:
          var: repos
      - name: Enable repos for RHEL7
        command: subscription-manager repos --disable="*" --enable={{ repos }} 
        when: ansible_distribution_major_version == "7"
    
      - name: Enable repo for RHEL 6
        command: subscription-manager repos --disable="*" --enable="rhel-6-server-rpms"
        when: ansible_distribution_major_version == "6"
      tags: [ repos ]
    
    - name: Create /var/log/journal directory
      file: path=/var/log/journal state=directory mode=2755 owner=0 group=190 #root:systemd-journal
      when: ansible_distribution_major_version == "7"

    - name: Install misc packages
      package:
        name: screen,vim-enhanced,libselinux-python
        state: present

    - name: Setup screen for scroll wheel
      copy:
        content: |
          # jcall - Setup terminal for mouse scroll wheel
          termcapinfo xterm* ti@:te@
        dest: /root/.screenrc

    - name: Setup BASH history
      lineinfile:
        path: /root/.bashrc
        line: "{{ item }}"
      with_items:
        - "alias vi='vim'"
        - "alias screen='screen -T xterm-256color'"
