---
- hosts: rhvm
  gather_facts: yes
  vars_files:
    - "{{ ansible_domain }}/rhvm-vault.yml"

  tasks:
    - name: Login to RHV
      ovirt_auth:
        url: "{{ rhvurl }}"
        insecure: yes
        username: "{{ rhvuser }}"
        password: "{{ rhvpass }}"

    - ovirt_hosts_facts:
        #pattern: name=host* and datacenter=west
        pattern: '*'
        auth: "{{ ovirt_auth }}"
    - debug:
        var: ovirt_hosts

    - name: Cleanup RHV auth token
      ovirt_auth:
        ovirt_auth: "{{ ovirt_auth }}"
        state: absent
