---
- hosts: tang
  tasks:
  - name: Install the tang RPM on the tang server
    yum:
      name: tang
      state: latest

  - name: Enable and start the tangd socket
    systemd:
      name: tangd.socket
      state: started
      enabled: yes

  - name: Open http port (80) on tang server - test with curl http://tang/adv
    firewalld:
      port: 80/tcp
      state: enabled
      immediate: yes
      permanent: yes



- hosts: server1
  tasks:
  - name: Install the clevis and VDO RPMs on server1
    yum:
      name: 
        - jq
        - clevis-dracut
        - clevis-systemd
        - vdo
        - kmod-kvdo
        - cryptsetup-reencrypt
      state: latest
