---
- hosts: tang
  tasks:
  - name: Install tang packages on tang server
    yum:
      name: tang
      state: latest

  - name: Enable and start the tangd socket
    systemd:
      name: tangd.socket
      enabled: yes
      state: started

  - name: Apply fix for missing Key Derivation Key
    systemd:
      name: tangd-update
      state: restarted

  - name: Open port 80 on tang server - test with curl http://tang/adv
    firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled
      immediate: yes

- hosts: server1
  tasks:
  - name: Install the clevis and vdo packages on the storage server
    yum:
      name: 
        - jq
        - clevis-dracut
        - clevis-systemd
        - vdo
        - kmod-kvdo
        - cryptsetup-reencrypt
      state: latest
