---
- hosts: tang
  tasks:
  - name: Install tang packages on tang server
    yum:
      name: tang
      state: latest

  - name: Set selinux to permissive
    selinux:
      policy: targeted
      state: permissive

  - name: Enable and start the tangd socket
    systemd:
      name: tangd.socket
      enabled: yes
      state: started

  - name: Open port 80 on tang server - test with curl http://tang/adv
    firewalld:
      port: 80/tcp
      permanent: yes
      state: enabled
      immediate: yes

- hosts: server1
  tasks:
  - name: Install the clevis and vdo packages on the storage server
    yum:
      name: 
        - libjose
        - jose
        - libluksmeta
        - luksmeta
        - clevis
        - clevis-dracut
        - clevis-luks
        - clevis-systemd
        - jq
        - cryptsetup-reencrypt
        - vdo
        - kmod-kvdo
      state: latest
